#!/bin/sh
set -eu

REPOSITORY="TheFunny233/SBoardNode"
BINARY_PATH="/usr/local/bin/sboardnode"
CONFIG_DIR="/etc/sboardnode"
CONFIG_PATH="$CONFIG_DIR/config.json"
ENV_PATH="$CONFIG_DIR/environment"
CORE_ENV_PATH="$CONFIG_DIR/core-environment"

VERSION="${SBOARDNODE_VERSION:-latest}"
SERVER="${SBOARD_SERVER:-}"
NODE_ID="${SBOARD_NODE_ID:-}"
TOKEN="${SBOARD_TOKEN:-}"
HEARTBEAT_INTERVAL="${SBOARD_HEARTBEAT_INTERVAL:-60}"
GO_MEM_LIMIT="${GOMEMLIMIT:-}"
GO_GC="${GOGC:-}"
CORE_MEMORY_TUNING="${SBOARD_CORE_MEMORY_TUNING:-1}"
CORE_GO_MEM_LIMIT="${SBOARD_CORE_GOMEMLIMIT:-}"
CORE_GO_GC="${SBOARD_CORE_GOGC:-}"
LOCAL_BINARY=""
CONFIG_ARGUMENTS=0
RUNTIME_ARGUMENTS=0
CORE_RUNTIME_ARGUMENTS=0

log() {
    printf '%s\n' "sboardnode installer: $*"
}

fail() {
    printf '%s\n' "sboardnode installer: error: $*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
Usage: install.sh [options]

Options:
  --server URL                SBoard base URL
  --node-id ID                Agent node ID generated by SBoard
  --token TOKEN               Agent token generated by SBoard
  --heartbeat-interval SEC    Heartbeat interval, 10-3600 (default: 60)
  --version VERSION           Release tag, for example v0.1.0 (default: latest)
  --gomemlimit VALUE          Agent Go soft memory limit (default: auto)
  --gogc VALUE                Go GC target percentage or off (default: 50)
  --core-gomemlimit VALUE     Xray Go soft memory limit or auto (default: auto)
  --core-gogc VALUE           Xray Go GC target percentage or off (default: 50)
  --no-core-memory-tuning     Do not manage Xray runtime memory settings
  --binary-file PATH          Install a local binary instead of downloading
  -h, --help                  Show this help

If configuration values are omitted during the first installation, the script
prompts on /dev/tty. Existing configuration and runtime tuning are preserved on
upgrade unless replacement values are supplied.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --server) SERVER="${2:-}"; CONFIG_ARGUMENTS=1; shift 2 ;;
        --node-id) NODE_ID="${2:-}"; CONFIG_ARGUMENTS=1; shift 2 ;;
        --token) TOKEN="${2:-}"; CONFIG_ARGUMENTS=1; shift 2 ;;
        --heartbeat-interval) HEARTBEAT_INTERVAL="${2:-}"; CONFIG_ARGUMENTS=1; shift 2 ;;
        --version) VERSION="${2:-}"; shift 2 ;;
        --gomemlimit) GO_MEM_LIMIT="${2:-}"; RUNTIME_ARGUMENTS=1; shift 2 ;;
        --gogc) GO_GC="${2:-}"; RUNTIME_ARGUMENTS=1; shift 2 ;;
        --core-gomemlimit) CORE_GO_MEM_LIMIT="${2:-}"; CORE_RUNTIME_ARGUMENTS=1; shift 2 ;;
        --core-gogc) CORE_GO_GC="${2:-}"; CORE_RUNTIME_ARGUMENTS=1; shift 2 ;;
        --no-core-memory-tuning) CORE_MEMORY_TUNING=0; CORE_RUNTIME_ARGUMENTS=1; shift ;;
        --binary-file) LOCAL_BINARY="${2:-}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) fail "unknown option: $1" ;;
    esac
done

[ "$(id -u)" -eq 0 ] || fail "run this installer as root"

case "$HEARTBEAT_INTERVAL" in
    *[!0-9]*|'') fail "heartbeat interval must be an integer" ;;
esac
[ "$HEARTBEAT_INTERVAL" -ge 10 ] && [ "$HEARTBEAT_INTERVAL" -le 3600 ] || \
    fail "heartbeat interval must be between 10 and 3600"
case "$CORE_MEMORY_TUNING" in
    0|1) ;;
    *) fail "SBOARD_CORE_MEMORY_TUNING must be 0 or 1" ;;
esac

TEMP_DIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT INT TERM

download() {
    url="$1"
    destination="$2"
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL --retry 3 --connect-timeout 10 "$url" -o "$destination"
    elif command -v wget >/dev/null 2>&1; then
        wget -q -T 20 -O "$destination" "$url"
    else
        fail "curl or wget is required"
    fi
}

architecture() {
    case "$(uname -m)" in
        x86_64|amd64) printf '%s' amd64 ;;
        aarch64|arm64) printf '%s' arm64 ;;
        armv7l|armv7) printf '%s' armv7 ;;
        *) fail "unsupported architecture: $(uname -m)" ;;
    esac
}

install_binary() {
    source_path="$LOCAL_BINARY"
    if [ -z "$source_path" ]; then
        arch="$(architecture)"
        asset="sboardnode-linux-$arch"
        if [ "$VERSION" = "latest" ]; then
            base_url="https://github.com/$REPOSITORY/releases/latest/download"
        else
            case "$VERSION" in v*) tag="$VERSION" ;; *) tag="v$VERSION" ;; esac
            base_url="https://github.com/$REPOSITORY/releases/download/$tag"
        fi
        log "downloading $asset ($VERSION)"
        download "$base_url/$asset" "$TEMP_DIR/$asset"
        download "$base_url/sha256sums.txt" "$TEMP_DIR/sha256sums.txt"
        if ! (cd "$TEMP_DIR" && grep "  $asset\$" sha256sums.txt | sha256sum -c - >/dev/null); then
            fail "binary checksum verification failed"
        fi
        source_path="$TEMP_DIR/$asset"
    else
        [ -f "$source_path" ] || fail "local binary does not exist: $source_path"
    fi
    cp "$source_path" "$TEMP_DIR/sboardnode.install"
    chmod 0755 "$TEMP_DIR/sboardnode.install"
    mv "$TEMP_DIR/sboardnode.install" "$BINARY_PATH"
}

prompt_value() {
    prompt="$1"
    hidden="$2"
    if ! { : < /dev/tty; } 2>/dev/null; then
        fail "$prompt is required; pass it as an installer option"
    fi
    printf '%s: ' "$prompt" > /dev/tty
    if [ "$hidden" = "yes" ]; then
        stty -echo < /dev/tty 2>/dev/null || true
    fi
    IFS= read -r value < /dev/tty || value=""
    if [ "$hidden" = "yes" ]; then
        stty echo < /dev/tty 2>/dev/null || true
        printf '\n' > /dev/tty
    fi
    printf '%s' "$value"
}

json_escape() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_config() {
    mkdir -p "$CONFIG_DIR"
    chmod 0750 "$CONFIG_DIR"
    if [ -f "$CONFIG_PATH" ] && [ "$CONFIG_ARGUMENTS" -eq 0 ] && \
       [ -z "$SERVER$NODE_ID$TOKEN" ]; then
        log "preserving existing $CONFIG_PATH"
        return
    fi
    [ -n "$SERVER" ] || SERVER="$(prompt_value "SBoard server URL" no)"
    [ -n "$NODE_ID" ] || NODE_ID="$(prompt_value "Node ID" no)"
    [ -n "$TOKEN" ] || TOKEN="$(prompt_value "Agent token" yes)"
    [ -n "$SERVER" ] && [ -n "$NODE_ID" ] && [ -n "$TOKEN" ] || \
        fail "server, node ID and token are required"
    case "$SERVER" in http://*|https://*) ;; *) fail "server must start with http:// or https://" ;; esac
    if [ -f "$CONFIG_PATH" ]; then
        cp "$CONFIG_PATH" "$CONFIG_PATH.bak"
        chmod 0600 "$CONFIG_PATH.bak"
    fi
    umask 077
    config_temp="$CONFIG_PATH.tmp.$$"
    printf '{\n  "server": "%s",\n  "node_id": "%s",\n  "token": "%s",\n  "heartbeat_interval": %s\n}\n' \
        "$(json_escape "$SERVER")" \
        "$(json_escape "$NODE_ID")" \
        "$(json_escape "$TOKEN")" \
        "$HEARTBEAT_INTERVAL" > "$config_temp"
    chmod 0600 "$config_temp"
    mv "$config_temp" "$CONFIG_PATH"
}

read_environment_value() {
    key="$1"
    environment_path="$2"
    if [ -f "$environment_path" ]; then
        sed -n "s/^$key=//p" "$environment_path" | tail -n 1
    fi
}

memory_file_mib() {
    awk '
        NR == 1 && $1 ~ /^[0-9]+$/ {
            bytes = $1 + 0
            if (bytes > 0 && bytes < 9223372036854771712) {
                print int(bytes / 1048576)
            }
            exit
        }
    ' "$1" 2>/dev/null
}

effective_memory_mib() {
    memory_effective="$(awk '/^MemTotal:/{print int($2 / 1024); exit}' /proc/meminfo 2>/dev/null)"
    case "$memory_effective" in *[!0-9]*|'') memory_effective=128 ;; esac
    [ "$memory_effective" -gt 0 ] || memory_effective=128

    memory_cgroup_v2="$(awk -F: '$1 == "0" {print $3; exit}' /proc/self/cgroup 2>/dev/null)"
    memory_cgroup_v1="$(awk -F: '$2 ~ /(^|,)memory(,|$)/ {print $3; exit}' /proc/self/cgroup 2>/dev/null)"
    for memory_file in \
        "/sys/fs/cgroup${memory_cgroup_v2}/memory.max" \
        "/sys/fs/cgroup${memory_cgroup_v2}/memory.high" \
        /sys/fs/cgroup/memory.max \
        /sys/fs/cgroup/memory.high \
        "/sys/fs/cgroup/memory${memory_cgroup_v1}/memory.limit_in_bytes" \
        "/sys/fs/cgroup${memory_cgroup_v1}/memory.limit_in_bytes" \
        /sys/fs/cgroup/memory/memory.limit_in_bytes
    do
        [ -r "$memory_file" ] || continue
        memory_candidate="$(memory_file_mib "$memory_file")"
        case "$memory_candidate" in *[!0-9]*|'') continue ;; esac
        if [ "$memory_candidate" -gt 0 ] && [ "$memory_candidate" -lt "$memory_effective" ]; then
            memory_effective="$memory_candidate"
        fi
    done
    printf '%s' "$memory_effective"
}

agent_memory_limit() {
    memory_total="$1"
    if [ "$memory_total" -le 256 ]; then
        memory_limit=20
    elif [ "$memory_total" -le 512 ]; then
        memory_limit=24
    else
        memory_limit=32
    fi
    printf '%sMiB' "$memory_limit"
}

core_memory_limit() {
    memory_total="$1"
    if [ "$memory_total" -le 128 ]; then
        memory_limit=$((memory_total * 5 / 16))
        [ "$memory_limit" -ge 32 ] || memory_limit=32
    else
        memory_limit=$((memory_total / 2))
        [ "$memory_limit" -le 512 ] || memory_limit=512
    fi
    printf '%sMiB' "$memory_limit"
}

validate_gomemlimit() {
    case "$1" in
        off) ;;
        *[!A-Za-z0-9.]*|'') fail "$2 must be a Go memory value such as 20MiB, or off" ;;
    esac
}

validate_gogc() {
    case "$1" in
        off) ;;
        *[!0-9]*|'') fail "$2 must be a non-negative integer or off" ;;
    esac
}

validate_runtime_settings() {
    runtime_mem_limit="$1"
    runtime_gc="$2"
    runtime_label="$3"
    if ! env GOMEMLIMIT="$runtime_mem_limit" GOGC="$runtime_gc" \
        "$BINARY_PATH" -version >/dev/null 2>&1; then
        fail "$runtime_label runtime rejected GOMEMLIMIT=$runtime_mem_limit or GOGC=$runtime_gc"
    fi
}

write_environment() {
    mkdir -p "$CONFIG_DIR"
    if [ -f "$ENV_PATH" ] && [ "$RUNTIME_ARGUMENTS" -eq 0 ] && \
       [ -z "$GO_MEM_LIMIT$GO_GC" ]; then
        log "preserving existing $ENV_PATH"
        return
    fi
    [ -n "$GO_MEM_LIMIT" ] || GO_MEM_LIMIT="$(read_environment_value GOMEMLIMIT "$ENV_PATH")"
    [ -n "$GO_GC" ] || GO_GC="$(read_environment_value GOGC "$ENV_PATH")"
    [ -n "$GO_MEM_LIMIT" ] || GO_MEM_LIMIT="auto"
    [ -n "$GO_GC" ] || GO_GC="50"
    if [ "$GO_MEM_LIMIT" = "auto" ]; then
        EFFECTIVE_MEMORY_MIB="$(effective_memory_mib)"
        GO_MEM_LIMIT="$(agent_memory_limit "$EFFECTIVE_MEMORY_MIB")"
        log "effective memory ${EFFECTIVE_MEMORY_MIB}MiB; agent GOMEMLIMIT=$GO_MEM_LIMIT"
    fi
    validate_gomemlimit "$GO_MEM_LIMIT" "GOMEMLIMIT"
    validate_gogc "$GO_GC" "GOGC"
    validate_runtime_settings "$GO_MEM_LIMIT" "$GO_GC" "Agent"
    umask 077
    environment_temp="$ENV_PATH.tmp.$$"
    printf 'GOMEMLIMIT=%s\nGOGC=%s\n' "$GO_MEM_LIMIT" "$GO_GC" > "$environment_temp"
    chmod 0600 "$environment_temp"
    mv "$environment_temp" "$ENV_PATH"
}

write_core_environment() {
    [ "$CORE_MEMORY_TUNING" = "1" ] || return 0
    mkdir -p "$CONFIG_DIR"
    if [ -f "$CORE_ENV_PATH" ] && [ "$CORE_RUNTIME_ARGUMENTS" -eq 0 ] && \
       [ -z "$CORE_GO_MEM_LIMIT$CORE_GO_GC" ]; then
        log "preserving existing $CORE_ENV_PATH"
        return
    fi
    [ -n "$CORE_GO_MEM_LIMIT" ] || CORE_GO_MEM_LIMIT="$(read_environment_value GOMEMLIMIT "$CORE_ENV_PATH")"
    [ -n "$CORE_GO_GC" ] || CORE_GO_GC="$(read_environment_value GOGC "$CORE_ENV_PATH")"
    [ -n "$CORE_GO_MEM_LIMIT" ] || CORE_GO_MEM_LIMIT="auto"
    [ -n "$CORE_GO_GC" ] || CORE_GO_GC="50"
    if [ "$CORE_GO_MEM_LIMIT" = "auto" ]; then
        EFFECTIVE_MEMORY_MIB="$(effective_memory_mib)"
        CORE_GO_MEM_LIMIT="$(core_memory_limit "$EFFECTIVE_MEMORY_MIB")"
        log "effective memory ${EFFECTIVE_MEMORY_MIB}MiB; Xray GOMEMLIMIT=$CORE_GO_MEM_LIMIT"
    fi
    validate_gomemlimit "$CORE_GO_MEM_LIMIT" "core GOMEMLIMIT"
    validate_gogc "$CORE_GO_GC" "core GOGC"
    validate_runtime_settings "$CORE_GO_MEM_LIMIT" "$CORE_GO_GC" "Xray"
    umask 077
    core_environment_temp="$CORE_ENV_PATH.tmp.$$"
    printf 'GOMEMLIMIT=%s\nGOGC=%s\n' "$CORE_GO_MEM_LIMIT" "$CORE_GO_GC" > "$core_environment_temp"
    chmod 0600 "$core_environment_temp"
    mv "$core_environment_temp" "$CORE_ENV_PATH"
}

install_systemd() {
    mkdir -p /etc/systemd/system
    cat > /etc/systemd/system/sboardnode.service <<'EOF'
[Unit]
Description=SBoard lightweight node agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
EnvironmentFile=-/etc/sboardnode/environment
ExecStart=/usr/local/bin/sboardnode -config /etc/sboardnode/config.json
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now sboardnode.service
    systemctl restart sboardnode.service
    log "installed systemd service"
}

install_openrc() {
    mkdir -p /etc/init.d
    cat > /etc/init.d/sboardnode <<'EOF'
#!/sbin/openrc-run

description="SBoard lightweight node agent"
command="/usr/local/bin/sboardnode"
command_args="-config /etc/sboardnode/config.json"
command_user="root:root"
supervisor="supervise-daemon"
respawn_delay=5
respawn_max=0

if [ -r /etc/sboardnode/environment ]; then
    set -a
    . /etc/sboardnode/environment
    set +a
fi

depend() {
    need net
    after firewall
}
EOF
    chmod 0755 /etc/init.d/sboardnode
    rc-update add sboardnode default >/dev/null
    rc-service sboardnode restart
    log "installed OpenRC service"
}

write_openrc_core_override() {
    mkdir -p /etc/conf.d
    openrc_core_config="/etc/conf.d/xray"
    openrc_core_temp="$(mktemp /etc/conf.d/.xray.sboardnode.XXXXXX)"
    if [ -f "$openrc_core_config" ]; then
        awk '
            $0 == "# BEGIN SBOARDNODE CORE MEMORY" { skip = 1; next }
            $0 == "# END SBOARDNODE CORE MEMORY" { skip = 0; next }
            !skip { print }
        ' "$openrc_core_config" > "$openrc_core_temp"
    fi
    if [ "$CORE_MEMORY_TUNING" = "1" ]; then
        printf '%s\n' \
            '# BEGIN SBOARDNODE CORE MEMORY' \
            'if [ -r /etc/sboardnode/core-environment ]; then' \
            '    set -a' \
            '    . /etc/sboardnode/core-environment' \
            '    set +a' \
            'fi' \
            '# END SBOARDNODE CORE MEMORY' >> "$openrc_core_temp"
    fi
    chmod 0600 "$openrc_core_temp"
    mv "$openrc_core_temp" "$openrc_core_config"
}

install_core_memory_tuning() {
    if [ "$CORE_MEMORY_TUNING" = "0" ]; then
        rm -f "$CORE_ENV_PATH"
        log "Xray memory tuning disabled"
    fi

    if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
        systemd_core_override="/etc/systemd/system/xray.service.d/20-sboardnode-memory.conf"
        if [ "$CORE_MEMORY_TUNING" = "1" ]; then
            mkdir -p "$(dirname "$systemd_core_override")"
            systemd_core_temp="$systemd_core_override.tmp.$$"
            printf '%s\n' \
                '[Service]' \
                'EnvironmentFile=-/etc/sboardnode/core-environment' > "$systemd_core_temp"
            chmod 0644 "$systemd_core_temp"
            mv "$systemd_core_temp" "$systemd_core_override"
            log "installed Xray systemd memory policy"
        else
            rm -f "$systemd_core_override"
        fi
        systemctl daemon-reload
        if systemctl is-active --quiet xray.service; then
            systemctl restart xray.service || fail "Xray failed to restart with the memory policy"
        fi
    elif command -v rc-service >/dev/null 2>&1; then
        write_openrc_core_override
        if [ -x /etc/init.d/xray ] && rc-service xray status >/dev/null 2>&1; then
            rc-service xray restart || fail "Xray failed to restart with the memory policy"
        fi
        [ "$CORE_MEMORY_TUNING" = "0" ] || log "installed Xray OpenRC memory policy"
    else
        [ "$CORE_MEMORY_TUNING" = "0" ] || \
            log "Xray memory policy saved but no supported core service was found"
    fi
}

install_service() {
    if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
        install_systemd
    elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then
        install_openrc
    else
        fail "supported init system not found (OpenRC or systemd required)"
    fi
}

install_binary
write_config
write_environment
write_core_environment
install_core_memory_tuning
install_service

log "installation complete"
log "config: $CONFIG_PATH"
log "runtime limits: $ENV_PATH"
[ "$CORE_MEMORY_TUNING" = "0" ] || log "Xray runtime limits: $CORE_ENV_PATH"
